import { GameItem } from "@/types";

// ============================================================================
// DAFTAR HARGA TOP-UP SEMUA GAME
// ============================================================================
// CARA EDIT HARGA:
// 1. Cari nama game yang ingin Anda edit
// 2. Edit langsung di bagian "price" untuk mengubah harga
// 3. Edit "name" untuk mengubah nama item (misal: "86 Diamonds")
//
// CARA TAMBAH ITEM BARU:
// 1. Copy salah satu baris item { ... }
// 2. Paste di bawahnya
// 3. Edit id, name, dan price
// 4. Jangan lupa tambahkan koma (,) di akhir
//
// CARA HAPUS ITEM:
// 1. Hapus seluruh baris { ... }, termasuk komanya
//
// FORMAT:
// {
//   id: "ml-1",                    // ID unik (jangan diubah)
//   gameId: "mobile-legends",      // ID game (harus sama dengan ID di games.ts)
//   name: "86 Diamonds",           // Nama item yang ditampilkan
//   price: 20000,                  // HARGA (edit ini)
//   stock: 100,                    // Stok (100 = unlimited)
//   description: "Basic Package"   // Deskripsi singkat
// }
// ============================================================================

export const gameItems: Record<string, GameItem[]> = {
  // ==========================================================================
  // MOBILE LEGENDS
  // ==========================================================================
  "mobile-legends": [
    {
      id: "ml-membership-1",
      gameId: "mobile-legends",
      name: "MOBILE LEGEND WEEKLY Diamond Pass",
      price: 28200,
      stock: 100,
      description: "Weekly Diamond Pass",
      category: "membership",
    },
    {
      id: "ml-membership-2",
      gameId: "mobile-legends",
      name: "MOBILE LEGEND WEEKLY Diamond Pass x2",
      price: 56400,
      stock: 100,
      description: "Weekly Diamond Pass x2",
      category: "membership",
    },
    {
      id: "ml-membership-3",
      gameId: "mobile-legends",
      name: "MOBILE LEGEND WEEKLY Diamond Pass x3",
      price: 84600,
      stock: 100,
      description: "Weekly Diamond Pass x3",
      category: "membership",
    },
    {
      id: "ml-membership-4",
      gameId: "mobile-legends",
      name: "MOBILE LEGEND WEEKLY Diamond Pass x4",
      price: 112800,
      stock: 100,
      description: "Weekly Diamond Pass x4",
      category: "membership",
    },
    {
      id: "ml-membership-5",
      gameId: "mobile-legends",
      name: "MOBILE LEGEND WEEKLY Diamond Pass x5",
      price: 141000,
      stock: 100,
      description: "Weekly Diamond Pass x5",
      category: "membership",
    },
    {
      id: "ml-membership-6",
      gameId: "mobile-legends",
      name: "MOBILE LEGEND Twilight Pass",
      price: 150800,
      stock: 100,
      description: "Twilight Pass",
      category: "membership",
    },
    {
      id: "ml-1",
      gameId: "mobile-legends",
      name: "86 Diamond",
      price: 23290,
      stock: 100,
      description: "Basic Package",
      category: "diamond",
    },
    {
      id: "ml-2",
      gameId: "mobile-legends",
      name: "173 Diamond",
      price: 46600,
      stock: 100,
      description: "Standard Package",
      category: "diamond",
    },
    {
      id: "ml-3",
      gameId: "mobile-legends",
      name: "258 Diamond",
      price: 69870,
      stock: 100,
      description: "Premium Package",
      category: "diamond",
    },
    {
      id: "ml-4",
      gameId: "mobile-legends",
      name: "345 Diamond",
      price: 93160,
      stock: 100,
      description: "Elite Package",
      category: "diamond",
    },
    {
      id: "ml-5",
      gameId: "mobile-legends",
      name: "429 Diamond",
      price: 116250,
      stock: 100,
      description: "Master Package",
      category: "diamond",
    },
    {
      id: "ml-6",
      gameId: "mobile-legends",
      name: "518 Diamond",
      price: 140100,
      stock: 100,
      description: "Legend Package",
      category: "diamond",
    },
    {
      id: "ml-7",
      gameId: "mobile-legends",
      name: "600 Diamond",
      price: 162200,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-8",
      gameId: "mobile-legends",
      name: "666 Diamond",
      price: 177500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-9",
      gameId: "mobile-legends",
      name: "792 Diamond",
      price: 213200,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-10",
      gameId: "mobile-legends",
      name: "882 Diamond",
      price: 233928,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-11",
      gameId: "mobile-legends",
      name: "966 Diamond",
      price: 256700,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-12",
      gameId: "mobile-legends",
      name: "1084 Diamond",
      price: 280300,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-13",
      gameId: "mobile-legends",
      name: "1135 Diamond",
      price: 301700,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-14",
      gameId: "mobile-legends",
      name: "1159 Diamond (Misi 1000 Diamond)",
      price: 307950,
      stock: 100,
      description: "Special Mission Package",
      category: "diamond",
    },
    {
      id: "ml-15",
      gameId: "mobile-legends",
      name: "1220 Diamond",
      price: 326700,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-16",
      gameId: "mobile-legends",
      name: "1358 Diamond",
      price: 360100,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-17",
      gameId: "mobile-legends",
      name: "1506 Diamond",
      price: 403600,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-18",
      gameId: "mobile-legends",
      name: "1704 Diamond",
      price: 452800,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-19",
      gameId: "mobile-legends",
      name: "2011 Diamond",
      price: 504500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-20",
      gameId: "mobile-legends",
      name: "2380 Diamond",
      price: 605400,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-21",
      gameId: "mobile-legends",
      name: "2539 Diamond",
      price: 657000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-22",
      gameId: "mobile-legends",
      name: "2885 Diamond",
      price: 740300,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-23",
      gameId: "mobile-legends",
      name: "3158 Diamond",
      price: 815000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-24",
      gameId: "mobile-legends",
      name: "3423 Diamond",
      price: 882500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-25",
      gameId: "mobile-legends",
      name: "3738 Diamond",
      price: 976200,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-26",
      gameId: "mobile-legends",
      name: "4020 Diamond",
      price: 1014210,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-27",
      gameId: "mobile-legends",
      name: "4958 Diamond",
      price: 1265000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-28",
      gameId: "mobile-legends",
      name: "5138 Diamond",
      price: 1311600,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-29",
      gameId: "mobile-legends",
      name: "5398 Diamond",
      price: 1366926,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-30",
      gameId: "mobile-legends",
      name: "5952 Diamond",
      price: 1518950,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-31",
      gameId: "mobile-legends",
      name: "6030 Diamond",
      price: 1530100,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-32",
      gameId: "mobile-legends",
      name: "6840 Diamond",
      price: 1721500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-33",
      gameId: "mobile-legends",
      name: "7195 Diamond",
      price: 1805000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-34",
      gameId: "mobile-legends",
      name: "7659 Diamond",
      price: 1929900,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
        {
      id: "ml-35",
      gameId: "mobile-legends",
      name: "8850 Diamond",
      price: 2202500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
        {
      id: "ml-36",
      gameId: "mobile-legends",
      name: "9660 Diamond",
      price: 2431000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
        {
      id: "ml-37",
      gameId: "mobile-legends",
      name: "10050 Diamond",
      price: 2535000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-38",
      gameId: "mobile-legends",
      name: "11483 Diamond",
      price: 2804200,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-39",
      gameId: "mobile-legends",
      name: "14820 Diamond",
      price: 3675800,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ml-40",
      gameId: "mobile-legends",
      name: " 20100 Diamond",
      price: 5079950,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
  ],

  // ==========================================================================
  // FREE FIRE
  // ==========================================================================
  "free-fire": [
    // MEMBERSHIP
    {
      id: "ff-membership-1",
      gameId: "free-fire",
      name: "Free Fire BP Card",
      price: 42300,
      stock: 100,
      description: "Battle Pass Card",
      category: "membership",
    },
    {
      id: "ff-membership-2",
      gameId: "free-fire",
      name: "Free Fire Membership Mingguan",
      price: 28600,
      stock: 100,
      description: "Weekly Membership",
      category: "membership",
    },
    {
      id: "ff-membership-3",
      gameId: "free-fire",
      name: "Free Fire Mingguan + 140 Diamond",
      price: 48000,
      stock: 100,
      description: "Weekly Membership + 140 Diamond",
      category: "membership",
    },
    {
      id: "ff-membership-4",
      gameId: "free-fire",
      name: "Free Fire Mingguan x2",
      price: 57200,
      stock: 100,
      description: "Weekly Membership x2",
      category: "membership",
    },
    {
      id: "ff-membership-5",
      gameId: "free-fire",
      name: "Free Fire Mingguan x3",
      price: 85800,
      stock: 100,
      description: "Weekly Membership x3",
      category: "membership",
    },
    {
      id: "ff-membership-6",
      gameId: "free-fire",
      name: "Free Fire Mingguan x5",
      price: 141200,
      stock: 100,
      description: "Weekly Membership x5",
      category: "membership",
    },
    {
      id: "ff-membership-7",
      gameId: "free-fire",
      name: "Free Fire Membership Bulanan",
      price: 85990,
      stock: 100,
      description: "Monthly Membership",
      category: "membership",
    },
    {
      id: "ff-membership-8",
      gameId: "free-fire",
      name: "Free Fire Membership Bulanan x2",
      price: 171980,
      stock: 100,
      description: "Monthly Membership x2",
      category: "membership",
    },
    {
      id: "ff-membership-9",
      gameId: "free-fire",
      name: "Free Fire Membership Bulanan x3",
      price: 257970,
      stock: 100,
      description: "Monthly Membership x3",
      category: "membership",
    },
    {
      id: "ff-membership-10",
      gameId: "free-fire",
      name: "Free Fire Membership Bulanan x4",
      price: 343960,
      stock: 100,
      description: "Monthly Membership x4",
      category: "membership",
    },
    {
      id: "ff-membership-11",
      gameId: "free-fire",
      name: "Free Fire Membership Bulanan x5",
      price: 425950,
      stock: 100,
      description: "Monthly Membership x5",
      category: "membership",
    },
    // DIAMOND
    {
      id: "ff-1",
      gameId: "free-fire",
      name: "10 Diamond",
      price: 1710,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-2",
      gameId: "free-fire",
      name: "20 Diamond",
      price: 3420,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-3",
      gameId: "free-fire",
      name: "30 Diamond",
      price: 5130,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-4",
      gameId: "free-fire",
      name: "40 Diamond",
      price: 6840,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-5",
      gameId: "free-fire",
      name: "50 Diamond",
      price: 7000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-6",
      gameId: "free-fire",
      name: "60 Diamond",
      price: 8536,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-7",
      gameId: "free-fire",
      name: "70 Diamond",
      price: 9030,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-8",
      gameId: "free-fire",
      name: "80 Diamond",
      price: 10500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-9",
      gameId: "free-fire",
      name: "90 Diamond",
      price: 12511,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-10",
      gameId: "free-fire",
      name: "100 Diamond",
      price: 14279,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-11",
      gameId: "free-fire",
      name: "120 Diamond",
      price: 16024,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-12",
      gameId: "free-fire",
      name: "125 Diamond",
      price: 17019,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-13",
      gameId: "free-fire",
      name: "130 Diamond",
      price: 18012,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-14",
      gameId: "free-fire",
      name: "150 Diamond",
      price: 19999,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-15",
      gameId: "free-fire",
      name: "190 Diamond",
      price: 25500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-16",
      gameId: "free-fire",
      name: "230 Diamond",
      price: 31250,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-17",
      gameId: "free-fire",
      name: "260 Diamond",
      price: 34861,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-18",
      gameId: "free-fire",
      name: "300 Diamond",
      price: 40688,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-19",
      gameId: "free-fire",
      name: "355 Diamond",
      price: 47099,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-20",
      gameId: "free-fire",
      name: "375 Diamond",
      price: 50538,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-21",
      gameId: "free-fire",
      name: "405 Diamond",
      price: 53614,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-22",
      gameId: "free-fire",
      name: "455 Diamond",
      price: 61550,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-23",
      gameId: "free-fire",
      name: "500 Diamond",
      price: 67010,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-24",
      gameId: "free-fire",
      name: "545 Diamond",
      price: 72500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-25",
      gameId: "free-fire",
      name: "600 Diamond",
      price: 80230,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-26",
      gameId: "free-fire",
      name: "645 Diamond",
      price: 87212,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-27",
      gameId: "free-fire",
      name: "710 Diamond",
      price: 95906,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-28",
      gameId: "free-fire",
      name: "770 Diamond",
      price: 100800,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-29",
      gameId: "free-fire",
      name: "800 Diamond",
      price: 105409,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-30",
      gameId: "free-fire",
      name: "860 Diamond",
      price: 114700,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-31",
      gameId: "free-fire",
      name: "930 Diamond",
      price: 122500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-32",
      gameId: "free-fire",
      name: "1000 Diamond",
      price: 130500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-33",
      gameId: "free-fire",
      name: "1060 Diamond",
      price: 141071,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-34",
      gameId: "free-fire",
      name: "1145 Diamond",
      price: 151274,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-35",
      gameId: "free-fire",
      name: "1200 Diamond",
      price: 159902,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-36",
      gameId: "free-fire",
      name: "1215 Diamond",
      price: 161100,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-37",
      gameId: "free-fire",
      name: "1300 Diamond",
      price: 173318,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-38",
      gameId: "free-fire",
      name: "1450 Diamond",
      price: 188700,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-39",
      gameId: "free-fire",
      name: "1510 Diamond",
      price: 197400,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-40",
      gameId: "free-fire",
      name: "1800 Diamond",
      price: 237100,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-41",
      gameId: "free-fire",
      name: "1875 Diamond",
      price: 246000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-42",
      gameId: "free-fire",
      name: "2005 Diamond",
      price: 264500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-43",
      gameId: "free-fire",
      name: "2100 Diamond",
      price: 278800,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-44",
      gameId: "free-fire",
      name: "2180 Diamond",
      price: 284900,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-45",
      gameId: "free-fire",
      name: "2200 Diamond",
      price: 287500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-46",
      gameId: "free-fire",
      name: "2280 Diamond",
      price: 299700,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-47",
      gameId: "free-fire",
      name: "2355 Diamond",
      price: 309300,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-48",
      gameId: "free-fire",
      name: "2400 Diamond",
      price: 314500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-49",
      gameId: "free-fire",
      name: "2575 Diamond",
      price: 339900,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-50",
      gameId: "free-fire",
      name: "3000 Diamond",
      price: 395500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-51",
      gameId: "free-fire",
      name: "3310 Diamond",
      price: 436500,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-52",
      gameId: "free-fire",
      name: "3620 Diamond",
      price: 476000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-53",
      gameId: "free-fire",
      name: "3675 Diamond",
      price: 481400,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-54",
      gameId: "free-fire",
      name: "3800 Diamond",
      price: 496800,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-55",
      gameId: "free-fire",
      name: "4050 Diamond",
      price: 530000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-56",
      gameId: "free-fire",
      name: "4340 Diamond",
      price: 570000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-57",
      gameId: "free-fire",
      name: "4720 Diamond",
      price: 620000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-58",
      gameId: "free-fire",
      name: "4800 Diamond",
      price: 631000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-59",
      gameId: "free-fire",
      name: "5500 Diamond",
      price: 720000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-60",
      gameId: "free-fire",
      name: "6000 Diamond",
      price: 785000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-61",
      gameId: "free-fire",
      name: "6480 Diamond",
      price: 850000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-62",
      gameId: "free-fire",
      name: "6550 Diamond",
      price: 859000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-63",
      gameId: "free-fire",
      name: "7310 Diamond",
      price: 950000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-64",
      gameId: "free-fire",
      name: "7430 Diamond",
      price: 979000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-65",
      gameId: "free-fire",
      name: "7650 Diamond",
      price: 1009000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-66",
      gameId: "free-fire",
      name: "8010 Diamond",
      price: 1056000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-67",
      gameId: "free-fire",
      name: "8730 Diamond",
      price: 1150000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-68",
      gameId: "free-fire",
      name: "9290 Diamond",
      price: 1229000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-69",
      gameId: "free-fire",
      name: "9800 Diamond",
      price: 1292000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-70",
      gameId: "free-fire",
      name: "14580 Diamond",
      price: 1920000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-71",
      gameId: "free-fire",
      name: "36500 Diamond",
      price: 4700000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-72",
      gameId: "free-fire",
      name: "37050 Diamond",
      price: 4850000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
    {
      id: "ff-73",
      gameId: "free-fire",
      name: "73100 Diamond",
      price: 9500000,
      stock: 100,
      description: "Diamond Package",
      category: "diamond",
    },
  ],

  // ==========================================================================
  // PUBG MOBILE
  // ==========================================================================
  "pubg-mobile": [
    // MEMBERSHIP
    {
      id: "pubg-membership-1",
      gameId: "pubg-mobile",
      name: "PUBG Elite Pass Plus",
      price: 456000,
      stock: 100,
      description: "Elite Pass Plus",
      category: "membership",
    },
    // UC
    {
      id: "pubg-1",
      gameId: "pubg-mobile",
      name: "60 UC",
      price: 15500,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-2",
      gameId: "pubg-mobile",
      name: "120 UC",
      price: 31000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-3",
      gameId: "pubg-mobile",
      name: "180 UC",
      price: 46500,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-4",
      gameId: "pubg-mobile",
      name: "240 UC",
      price: 62000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-5",
      gameId: "pubg-mobile",
      name: "325 UC",
      price: 77300,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-6",
      gameId: "pubg-mobile",
      name: "385 UC",
      price: 92000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-7",
      gameId: "pubg-mobile",
      name: "445 UC",
      price: 107500,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-8",
      gameId: "pubg-mobile",
      name: "505 UC",
      price: 123200,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-9",
      gameId: "pubg-mobile",
      name: "565 UC",
      price: 138600,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-10",
      gameId: "pubg-mobile",
      name: "660 UC",
      price: 154400,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-11",
      gameId: "pubg-mobile",
      name: "720 UC",
      price: 170300,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-12",
      gameId: "pubg-mobile",
      name: "780 UC",
      price: 186000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-13",
      gameId: "pubg-mobile",
      name: "840 UC",
      price: 202000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-14",
      gameId: "pubg-mobile",
      name: "900 UC",
      price: 217000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-15",
      gameId: "pubg-mobile",
      name: "985 UC",
      price: 233000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-16",
      gameId: "pubg-mobile",
      name: "1105 UC",
      price: 264000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-17",
      gameId: "pubg-mobile",
      name: "1165 UC",
      price: 280000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-18",
      gameId: "pubg-mobile",
      name: "1320 UC",
      price: 310000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-19",
      gameId: "pubg-mobile",
      name: "1500 UC",
      price: 358000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-20",
      gameId: "pubg-mobile",
      name: "1800 UC",
      price: 390000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-21",
      gameId: "pubg-mobile",
      name: "1920 UC",
      price: 421000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-22",
      gameId: "pubg-mobile",
      name: "1980 UC",
      price: 437000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-23",
      gameId: "pubg-mobile",
      name: "2125 UC",
      price: 468000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-24",
      gameId: "pubg-mobile",
      name: "2460 UC",
      price: 547000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-25",
      gameId: "pubg-mobile",
      name: "2785 UC",
      price: 625000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-26",
      gameId: "pubg-mobile",
      name: "3120 UC",
      price: 704000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-27",
      gameId: "pubg-mobile",
      name: "3850 UC",
      price: 783000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-28",
      gameId: "pubg-mobile",
      name: "4030 UC",
      price: 829000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-29",
      gameId: "pubg-mobile",
      name: "4175 UC",
      price: 861000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-30",
      gameId: "pubg-mobile",
      name: "4510 UC",
      price: 939000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-31",
      gameId: "pubg-mobile",
      name: "4835 UC",
      price: 1018000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-32",
      gameId: "pubg-mobile",
      name: "5170 UC",
      price: 1095000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-33",
      gameId: "pubg-mobile",
      name: "5650 UC",
      price: 1166000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-34",
      gameId: "pubg-mobile",
      name: "5975 UC",
      price: 1250000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-35",
      gameId: "pubg-mobile",
      name: "6310 UC",
      price: 1330000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-36",
      gameId: "pubg-mobile",
      name: "6635 UC",
      price: 1410000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-37",
      gameId: "pubg-mobile",
      name: "6970 UC",
      price: 1487000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-38",
      gameId: "pubg-mobile",
      name: "8100 UC",
      price: 1560000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
    {
      id: "pubg-39",
      gameId: "pubg-mobile",
      name: "16200 UC",
      price: 3115000,
      stock: 100,
      description: "UC Package",
      category: "diamond",
    },
  ],

  // ==========================================================================
  // GENSHIN IMPACT
  // ==========================================================================
  "genshin-impact": [
    // MEMBERSHIP
    {
      id: "gi-membership-1",
      gameId: "genshin-impact",
      name: "Blessing of the Welkin Moon",
      price: 55500,
      stock: 100,
      description: "Welkin Moon",
      category: "membership",
    },
    {
      id: "gi-membership-2",
      gameId: "genshin-impact",
      name: "Blessing of the Welkin Moon x2",
      price: 111000,
      stock: 100,
      description: "Welkin Moon x2",
      category: "membership",
    },
    {
      id: "gi-membership-3",
      gameId: "genshin-impact",
      name: "Blessing of the Welkin Moon x3",
      price: 166500,
      stock: 100,
      description: "Welkin Moon x3",
      category: "membership",
    },
    {
      id: "gi-membership-4",
      gameId: "genshin-impact",
      name: "Blessing of the Welkin Moon x4",
      price: 222000,
      stock: 100,
      description: "Welkin Moon x4",
      category: "membership",
    },
    {
      id: "gi-membership-5",
      gameId: "genshin-impact",
      name: "Blessing of the Welkin Moon x5",
      price: 277500,
      stock: 100,
      description: "Welkin Moon x5",
      category: "membership",
    },
    // GENESIS CRYSTALS
    {
      id: "gi-1",
      gameId: "genshin-impact",
      name: "60 GC",
      price: 11000,
      stock: 100,
      description: "Genesis Crystals Package",
      category: "diamond",
    },
    {
      id: "gi-2",
      gameId: "genshin-impact",
      name: "330 (300 + 30) GC",
      price: 55000,
      stock: 100,
      description: "Genesis Crystals Package",
      category: "diamond",
    },
    {
      id: "gi-3",
      gameId: "genshin-impact",
      name: "1090 (980 + 110) GC",
      price: 172000,
      stock: 100,
      description: "Genesis Crystals Package",
      category: "diamond",
    },
    {
      id: "gi-4",
      gameId: "genshin-impact",
      name: "2240 (1980 + 260) GC",
      price: 362000,
      stock: 100,
      description: "Genesis Crystals Package",
      category: "diamond",
    },
    {
      id: "gi-5",
      gameId: "genshin-impact",
      name: "3880 (3280 + 600) GC",
      price: 589000,
      stock: 100,
      description: "Genesis Crystals Package",
      category: "diamond",
    },
    {
      id: "gi-6",
      gameId: "genshin-impact",
      name: "8080 (6480 + 1600) GC",
      price: 1130000,
      stock: 100,
      description: "Genesis Crystals Package",
      category: "diamond",
    },
  ],

  // ==========================================================================
  // VALORANT
  // ==========================================================================
  valorant: [
    {
      id: "val-1",
      gameId: "valorant",
      name: "475 VP",
      price: 55000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-2",
      gameId: "valorant",
      name: "1000 VP",
      price: 111000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-3",
      gameId: "valorant",
      name: "1475 VP",
      price: 168000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-4",
      gameId: "valorant",
      name: "2050 VP",
      price: 225000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-5",
      gameId: "valorant",
      name: "2525 VP",
      price: 282000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-6",
      gameId: "valorant",
      name: "3050 VP",
      price: 339000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-7",
      gameId: "valorant",
      name: "3650 VP",
      price: 392000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-8",
      gameId: "valorant",
      name: "4125 VP",
      price: 449000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-9",
      gameId: "valorant",
      name: "4650 VP",
      price: 506000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-10",
      gameId: "valorant",
      name: "5350 VP",
      price: 565000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-11",
      gameId: "valorant",
      name: "5700 VP",
      price: 620000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-12",
      gameId: "valorant",
      name: "5825 VP",
      price: 623000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-13",
      gameId: "valorant",
      name: "6350 VP",
      price: 679000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-14",
      gameId: "valorant",
      name: "7300 VP",
      price: 787000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-15",
      gameId: "valorant",
      name: "7400 VP",
      price: 792000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-16",
      gameId: "valorant",
      name: "11000 VP",
      price: 1110000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-17",
      gameId: "valorant",
      name: "11475 VP",
      price: 1162000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-18",
      gameId: "valorant",
      name: "12000 VP",
      price: 1215000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-19",
      gameId: "valorant",
      name: "13050 VP",
      price: 1330000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-20",
      gameId: "valorant",
      name: "14650 VP",
      price: 1500000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
    {
      id: "val-21",
      gameId: "valorant",
      name: "22000 VP",
      price: 2207000,
      stock: 100,
      description: "VP Package",
      category: "diamond",
    },
  ],

  // ==========================================================================
  // ROBLOX
  // ==========================================================================
  roblox: [
    // MEMBERSHIP / GIFT CARD
    {
      id: "roblox-membership-1",
      gameId: "roblox",
      name: "Roblox Gift Card IDR 50k",
      price: 47500,
      stock: 100,
      description: "Gift Card 50k",
      category: "membership",
    },
    {
      id: "roblox-membership-2",
      gameId: "roblox",
      name: "Roblox Gift Card IDR 60k",
      price: 62500,
      stock: 100,
      description: "Gift Card 60k",
      category: "membership",
    },
    {
      id: "roblox-membership-3",
      gameId: "roblox",
      name: "Roblox Gift Card IDR 100k",
      price: 90200,
      stock: 100,
      description: "Gift Card 100k",
      category: "membership",
    },
    {
      id: "roblox-membership-4",
      gameId: "roblox",
      name: "Roblox Gift Card IDR 300k",
      price: 280000,
      stock: 100,
      description: "Gift Card 300k",
      category: "membership",
    },
    {
      id: "roblox-membership-5",
      gameId: "roblox",
      name: "Roblox Gift Card IDR 500k",
      price: 470000,
      stock: 100,
      description: "Gift Card 500k",
      category: "membership",
    },
    // ROBUX
    {
      id: "roblox-1",
      gameId: "roblox",
      name: "250 Robux",
      price: 40500,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-2",
      gameId: "roblox",
      name: "500 Robux",
      price: 81000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-3",
      gameId: "roblox",
      name: "800 Robux",
      price: 129600,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-4",
      gameId: "roblox",
      name: "1000 Robux",
      price: 162000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-5",
      gameId: "roblox",
      name: "1500 Robux",
      price: 243000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-6",
      gameId: "roblox",
      name: "2000 Robux",
      price: 324000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-7",
      gameId: "roblox",
      name: "3000 Robux",
      price: 486000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-8",
      gameId: "roblox",
      name: "4500 Robux",
      price: 729000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
    {
      id: "roblox-9",
      gameId: "roblox",
      name: "10000 Robux",
      price: 1564000,
      stock: 100,
      description: "Robux Package",
      category: "diamond",
    },
  ],

  // ==========================================================================
  // 8 BALL POOL
  // ==========================================================================
  "8-ball-pool": [
    {
      id: "8bp-1",
      gameId: "8-ball-pool",
      name: "100 Cash",
      price: 15000,
      stock: 100,
      description: "Starter Package",
    },
    {
      id: "8bp-2",
      gameId: "8-ball-pool",
      name: "250 Cash",
      price: 35000,
      stock: 100,
      description: "Basic Package",
    },
    {
      id: "8bp-3",
      gameId: "8-ball-pool",
      name: "500 Cash",
      price: 65000,
      stock: 100,
      description: "Standard Package",
    },
    {
      id: "8bp-4",
      gameId: "8-ball-pool",
      name: "1200 Cash",
      price: 145000,
      stock: 100,
      description: "Premium Package",
    },
    {
      id: "8bp-5",
      gameId: "8-ball-pool",
      name: "2500 Cash",
      price: 290000,
      stock: 100,
      description: "Elite Package",
    },
  ],

  // ==========================================================================
  // ACE RACER
  // ==========================================================================
  "ace-racer": [
    {
      id: "ar-1",
      gameId: "ace-racer",
      name: "60 Tokens",
      price: 12700,
      stock: 100,
      description: "Starter Package",
    },
    {
      id: "ar-2",
      gameId: "ace-racer",
      name: "250 Tokens",
      price: 51500,
      stock: 100,
      description: "Basic Package",
    },
    {
      id: "ar-3",
      gameId: "ace-racer",
      name: "1180 Tokens",
      price: 230000,
      stock: 100,
      description: "Standard Package",
    },
    {
      id: "ar-4",
      gameId: "ace-racer",
      name: "2880 Tokens",
      price: 290000,
      stock: 100,
      description: "Premium Package",
    },
    {
      id: "ar-5",
      gameId: "ace-racer",
      name: "5880 Tokens",
      price: 152000,
      stock: 100,
      description: "Elite Package",
    },
  ],

  // ==========================================================================
  // AFK JOURNEY
  // ==========================================================================
  "afk-journey": [
    {
      id: "afkj-1",
      gameId: "afk-journey",
      name: "60 Gems",
      price: 15000,
      stock: 100,
      description: "Starter Package",
    },
    {
      id: "afkj-2",
      gameId: "afk-journey",
      name: "330 Gems",
      price: 75000,
      stock: 100,
      description: "Basic Package",
    },
    {
      id: "afkj-3",
      gameId: "afk-journey",
      name: "1090 Gems",
      price: 250000,
      stock: 100,
      description: "Standard Package",
    },
    {
      id: "afkj-4",
      gameId: "afk-journey",
      name: "3280 Gems",
      price: 750000,
      stock: 100,
      description: "Premium Package",
    },
    {
      id: "afkj-5",
      gameId: "afk-journey",
      name: "6560 Gems",
      price: 1500000,
      stock: 100,
      description: "Elite Package",
    },
  ],

  // ==========================================================================
  // HONKAI STAR RAIL
  // ==========================================================================
  "honkai-star-rail": [
    {
      id: "hsr-1",
      gameId: "honkai-star-rail",
      name: "60 Oneiric Shards",
      price: 15000,
      stock: 100,
      description: "Express Supply Pass",
    },
    {
      id: "hsr-2",
      gameId: "honkai-star-rail",
      name: "330 Oneiric Shards",
      price: 75000,
      stock: 100,
      description: "First Purchase Bonus",
    },
    {
      id: "hsr-3",
      gameId: "honkai-star-rail",
      name: "1090 Oneiric Shards",
      price: 250000,
      stock: 100,
      description: "Double Bonus",
    },
    {
      id: "hsr-4",
      gameId: "honkai-star-rail",
      name: "3280 Oneiric Shards",
      price: 750000,
      stock: 100,
      description: "Triple Bonus",
    },
    {
      id: "hsr-5",
      gameId: "honkai-star-rail",
      name: "6560 Oneiric Shards",
      price: 1500000,
      stock: 100,
      description: "Mega Bonus",
    },
  ],

  // ==========================================================================
  // ZENLESS ZONE ZERO
  // ==========================================================================
  "zenless-zone-zero": [
    {
      id: "zzz-1",
      gameId: "zenless-zone-zero",
      name: "60 Monochrome",
      price: 15000,
      stock: 100,
      description: "Inter-Knot Membership",
    },
    {
      id: "zzz-2",
      gameId: "zenless-zone-zero",
      name: "330 Monochrome",
      price: 75000,
      stock: 100,
      description: "First Time Bonus",
    },
    {
      id: "zzz-3",
      gameId: "zenless-zone-zero",
      name: "1090 Monochrome",
      price: 250000,
      stock: 100,
      description: "Double Bonus",
    },
    {
      id: "zzz-4",
      gameId: "zenless-zone-zero",
      name: "3280 Monochrome",
      price: 750000,
      stock: 100,
      description: "Triple Bonus",
    },
    {
      id: "zzz-5",
      gameId: "zenless-zone-zero",
      name: "6560 Monochrome",
      price: 1500000,
      stock: 100,
      description: "Mega Bonus",
    },
  ],

  // ==========================================================================
  // CALL OF DUTY MOBILE
  // ==========================================================================
  "call-of-duty-mobile": [
    {
      id: "codm-1",
      gameId: "call-of-duty-mobile",
      name: "80 CP",
      price: 20000,
      stock: 100,
      description: "Starter Package",
    },
    {
      id: "codm-2",
      gameId: "call-of-duty-mobile",
      name: "400 CP",
      price: 95000,
      stock: 100,
      description: "Basic Package",
    },
    {
      id: "codm-3",
      gameId: "call-of-duty-mobile",
      name: "800 CP",
      price: 185000,
      stock: 100,
      description: "Standard Package",
    },
    {
      id: "codm-4",
      gameId: "call-of-duty-mobile",
      name: "2000 CP",
      price: 450000,
      stock: 100,
      description: "Premium Package",
    },
    {
      id: "codm-5",
      gameId: "call-of-duty-mobile",
      name: "5000 CP",
      price: 1100000,
      stock: 100,
      description: "Elite Package",
    },
  ],

  // ==========================================================================
  // LEAGUE OF LEGENDS WILD RIFT
  // ==========================================================================
  "league-of-legends-wild-rift": [
    {
      id: "lolwr-1",
      gameId: "league-of-legends-wild-rift",
      name: "420 Wild Cores",
      price: 50000,
      stock: 100,
      description: "Starter Package",
    },
    {
      id: "lolwr-2",
      gameId: "league-of-legends-wild-rift",
      name: "700 Wild Cores",
      price: 80000,
      stock: 100,
      description: "Basic Package",
    },
    {
      id: "lolwr-3",
      gameId: "league-of-legends-wild-rift",
      name: "1375 Wild Cores",
      price: 150000,
      stock: 100,
      description: "Standard Package",
    },
    {
      id: "lolwr-4",
      gameId: "league-of-legends-wild-rift",
      name: "2800 Wild Cores",
      price: 300000,
      stock: 100,
      description: "Premium Package",
    },
    {
      id: "lolwr-5",
      gameId: "league-of-legends-wild-rift",
      name: "5850 Wild Cores",
      price: 600000,
      stock: 100,
      description: "Elite Package",
    },
  ],

  // ==========================================================================
  // RAGNAROK M: ETERNAL LOVE
  // ==========================================================================
  "ragnarok-m-eternal-love": [
    {
      id: "rom-1",
      gameId: "ragnarok-m-eternal-love",
      name: "60 Big Cat Coins",
      price: 12000,
      stock: 100,
      description: "Starter Package",
    },
    {
      id: "rom-2",
      gameId: "ragnarok-m-eternal-love",
      name: "120 Big Cat Coins",
      price: 23000,
      stock: 100,
      description: "Basic Package",
    },
    {
      id: "rom-3",
      gameId: "ragnarok-m-eternal-love",
      name: "300 Big Cat Coins",
      price: 55000,
      stock: 100,
      description: "Standard Package",
    },
    {
      id: "rom-4",
      gameId: "ragnarok-m-eternal-love",
      name: "600 Big Cat Coins",
      price: 110000,
      stock: 100,
      description: "Premium Package",
    },
    {
      id: "rom-5",
      gameId: "ragnarok-m-eternal-love",
      name: "1200 Big Cat Coins",
      price: 220000,
      stock: 100,
      description: "Elite Package",
    },
  ],
};

// ============================================================================
// CATATAN PENTING:
// ============================================================================
// 1. Setiap game ID harus SAMA PERSIS dengan ID di games.ts
// 2. Format harga: 20000 (tanpa titik atau koma)
// 3. Untuk menambah item, copy salah satu baris dan edit
// 4. Untuk menghapus item, hapus seluruh baris { ... },
// 5. Jangan lupa koma (,) di akhir setiap item (kecuali item terakhir dalam array)
// 6. Stock 100 = unlimited (bisa diubah sesuai kebutuhan)
// ============================================================================
